#!/usr/bin/env python3
"""
Generate test/uzlib_lzcopy/fixtures.h: a set of zlib-compressed payloads plus
the FNV-1a-64 hash and length of their original bytes, so the host uzlib test
can verify decompression without linking libz or embedding the raw payloads.

The payloads deliberately span the LZ-copy patterns that distinguish the two
tinflate.c copy variants:
  - dist1 / rle  : distance-1 (overlapping) runs -- the case the unclamped
                   memcpy() path corrupts; the correctness canary.
  - text_repeat  : long matches at large distances -- the bulk-copy win.
  - text_natural : many short matches.

Deterministic, so the committed header is stable. Re-run after changing this
script: python3 scripts/gen_uzlib_fixtures.py
"""
import os
import zlib

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "test", "uzlib_lzcopy", "fixtures.h")

RAW = 64 * 1024
FNV_OFFSET = 0xCBF29CE484222325
FNV_PRIME = 0x100000001B3
MASK64 = 0xFFFFFFFFFFFFFFFF


class Xorshift:
    """Tiny deterministic PRNG so fixtures don't depend on Python's RNG."""

    def __init__(self, seed=0x1234567):
        self.s = seed

    def next(self):
        x = self.s
        x ^= (x << 13) & 0xFFFFFFFF
        x ^= x >> 17
        x ^= (x << 5) & 0xFFFFFFFF
        self.s = x & 0xFFFFFFFF
        return self.s


def gen_dist1(_rng):
    return bytes([0x5A]) * RAW


def gen_rle(rng):
    out = bytearray()
    v = 0
    while len(out) < RAW:
        run = 8 + (rng.next() % 240)
        run = min(run, RAW - len(out))
        out += bytes([v]) * run
        v = (v + 1 + (rng.next() & 3)) & 0xFF
    return bytes(out)


def gen_text_repeat(_rng):
    para = (b"The quick brown fox jumps over the lazy dog. "
            b"Pack my box with five dozen liquor jugs. "
            b"How vexingly quick daft zebras jump! ")
    return (para * (RAW // len(para) + 1))[:RAW]


def gen_text_natural(rng):
    words = [b"the", b"of", b"and", b"a", b"to", b"in", b"is", b"that", b"it",
             b"for", b"reader", b"chapter", b"page", b"story", b"night",
             b"house", b"light", b"again", b"between", b"thought", b"morning",
             b"another", b"remember"]
    out = bytearray()
    while len(out) < RAW:
        out += words[rng.next() % len(words)]
        out += b"." if rng.next() % 8 == 0 else b" "
    return bytes(out[:RAW])


FIXTURES = [
    ("dist1 (single byte run)", gen_dist1),
    ("rle (dist-1 runs)", gen_rle),
    ("text repeated", gen_text_repeat),
    ("text natural", gen_text_natural),
]


def fnv1a(data):
    h = FNV_OFFSET
    for b in data:
        h = ((h ^ b) * FNV_PRIME) & MASK64
    return h


def c_array(name, data):
    lines = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main():
    parts = [
        "// AUTO-GENERATED by scripts/gen_uzlib_fixtures.py -- do not edit by hand.",
        "// Re-run: python3 scripts/gen_uzlib_fixtures.py",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "struct UzlibFixture {",
        "    const char* name;",
        "    const unsigned char* comp;  // zlib stream (2-byte header + deflate + adler)",
        "    size_t comp_len;",
        "    size_t raw_len;",
        "    uint64_t raw_fnv1a;",
        "};",
        "",
    ]
    entries = []
    for idx, (name, gen) in enumerate(FIXTURES):
        raw = gen(Xorshift())
        comp = zlib.compress(raw, 9)
        sym = f"fx_{idx}_comp"
        parts.append(c_array(sym, comp))
        parts.append("")
        entries.append(
            f'    {{"{name}", {sym}, sizeof({sym}), {len(raw)}, '
            f"0x{fnv1a(raw):016x}ULL}},"
        )
    parts.append("static const UzlibFixture kUzlibFixtures[] = {")
    parts.extend(entries)
    parts.append("};")
    parts.append("static const size_t kUzlibFixtureCount =")
    parts.append("    sizeof(kUzlibFixtures) / sizeof(kUzlibFixtures[0]);")
    parts.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(parts))
    print(f"wrote {OUT} ({len(FIXTURES)} fixtures)")


if __name__ == "__main__":
    main()
